---
- hosts: local
  vars:
    ansible_connection: ssh 
    ansible_ssh_user: root
    ansible_ssh_pass: root123

  tasks:
  - debug:
      var=topology
  
  - name: Create the list of networks
    set_fact:
      list_networks: "{{ list_networks | default ([]) + [item.key] }}"
    with_dict: "{{ topology.networks }}"

  - name: Create the list of networks
    set_fact:
      list_vms: "{{ list_vms | default ([]) + [item.key] }}"
    with_dict: "{{ topology.vms }}"
    
  - debug: var=list_networks
  - debug: var=list_vms

  - debug:
      msg: "{{ list_networks.0 }}"
      
  - debug:
      msg: "{{ topology.networks[list_networks.0].ip_subnet }}"
  
