global_configuration:
#  CONTAINER_REGISTRY: ci-repo.englab.juniper.net:5010
#  REGISTRY_PRIVATE_INSECURE: True
   CONTAINER_REGISTRY: hub.juniper.net/contrail
   CONTAINER_REGISTRY_USERNAME: JNPR-FieldUser3
   CONTAINER_REGISTRY_PASSWORD: "E6Ti-V_GhU0yH#umLanQ"
#   CONTAINER_REGISTRY: hub.juniper.net/contrail
#   CONTAINER_REGISTRY_USERNAME: JNPR-FieldUser1
#   CONTAINER_REGISTRY_PASSWORD: Mvb!%3D_+i*Gx0pQg8^4
#   REGISTRY_PRIVATE_INSECURE: True
provider_config:
  kvm:
    image: CentOS-7-x86_64-GenericCloud-1805.qcow2 
    image_url: http://10.84.5.120/cs-customer/images
    ssh_pwd: c0ntrail123
    ssh_user: root
    ssh_public_key:
    ssh_private_key:
    vcpu: 7
    vram: 49152
    vdisk: 150G
    subnet_prefix: 192.168.222.0
    subnet_netmask: 255.255.255.0
    gateway: 192.168.222.1
    nameserver: 192.168.222.1
    ntpserver: 10.84.5.100  
    domainsuffix: sdn.lab
instances:
  all-cont-dc-1:
    provider: kvm
    host: 10.87.65.27
    bridge: br-management
    ip: 192.168.222.151
    additional_interfaces:
      - bridge: br-lan-dc
        ip: 192.168.100.151
        mask: 255.255.255.0
    roles:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      openstack:
      openstack_compute:
      vrouter:
  all-cont-dc-2:
    provider: kvm
    host: 10.87.65.27
    bridge: br-management
    ip: 192.168.222.152
    additional_interfaces:
      - bridge: br-lan-dc
        ip: 192.168.100.152
        mask: 255.255.255.0
    roles:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      openstack:
  all-cont-dc-3:
    provider: kvm
    host: 10.87.65.27
    bridge: br-management
    ip: 192.168.222.153
    additional_interfaces:
      - bridge: br-lan-dc
        ip: 192.168.100.153
        mask: 255.255.255.0
    roles:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      openstack:
  cont-pop1-1:
    vcpu: 2
    vram: 8192
    vdisk: 20G
    provider: kvm
    host: 10.87.65.27
    bridge: br-management
    ip: 192.168.222.161
    additional_interfaces:
      - bridge: br-lan-dc
        ip: 192.168.100.161
        mask: 255.255.255.0
    roles:
      control_only:
        CONTROL_NODES: 192.168.100.161,192.168.100.162
        location: pop1
  cont-pop1-2:
    vcpu: 2
    vram: 8192
    vdisk: 20G
    provider: kvm
    host: 10.87.65.27
    bridge: br-management
    ip: 192.168.222.162
    additional_interfaces:
      - bridge: br-lan-dc
        ip: 192.168.100.162
        mask: 255.255.255.0
    roles:
      control_only:
        CONTROL_NODES: 192.168.100.161,192.168.100.162
        location: pop1
  comp-pop1-1:
    vcpu: 4
    vram: 16384
    vdisk: 20G
    provider: kvm
    host: 10.87.65.27
    bridge: br-management
    ip: 192.168.222.165
    additional_interfaces:
      - bridge: br-lan-p1
        ip: 192.168.101.165
        mask: 255.255.255.0
    roles:
      vrouter:
        CONTROL_NODES: 192.168.100.162,192.168.100.161
        location: pop1
        VROUTER_GATEWAY: 192.168.101.1
      openstack_compute:
  cont-pop2-1:
    vcpu: 2
    vram: 8192
    vdisk: 20G
    provider: kvm
    host: 10.87.65.27
    bridge: br-management
    ip: 192.168.222.171
    additional_interfaces:
      - bridge: br-lan-dc
        ip: 192.168.100.171
        mask: 255.255.255.0
    roles:
      control_only:
        CONTROL_NODES: 192.168.100.171,192.168.100.172
        location: pop2
  cont-pop2-2:
    vcpu: 2
    vram: 8192
    vdisk: 20G
    provider: kvm
    host: 10.87.65.27
    bridge: br-management
    ip: 192.168.222.172
    additional_interfaces:
      - bridge: br-lan-dc
        ip: 192.168.100.172
        mask: 255.255.255.0
    roles:
      control_only:
        CONTROL_NODES: 192.168.100.171,192.168.100.172
        location: pop2
  comp-pop2-1:
    vcpu: 4
    vram: 16384
    vdisk: 20G
    provider: kvm
    host: 10.87.65.27
    bridge: br-management
    ip: 192.168.222.175
    additional_interfaces:
      - bridge: br-lan-p2
        ip: 192.168.102.175
        mask: 255.255.255.0
    roles:
      vrouter:
        CONTROL_NODES: 192.168.100.172,192.168.100.171
        location: pop2
        VROUTER_GATEWAY: 192.168.102.1
      openstack_compute:
remote_locations:
  pop1:
    SUBCLUSTER: pop1
    BGP_ASN: 65002
  pop2:
    SUBCLUSTER: pop2
    BGP_ASN: 65002
contrail_configuration:
  CONFIG_DTABASE_NODEMGR__DEFAULTS__minimum_diskGB: "2"
  DATABASE_NODEMGR__DEFAULTS__minimum_diskGB: "2"
  OPENSTACK_VERSION: queens
  CONTRAIL_CONTAINER_TAG: 5.0.1-0.214-queens
  CONTROLLER_NODES: 192.168.100.151,192.168.100.152,192.168.100.153
  CONTROL_NODES: 192.168.100.151,192.168.100.152,192.168.100.153
#  AAA_MODE: cloud-admin
  UPGRADE_KERNEL: true
  CLOUD_ORCHESTRATOR: openstack
  VROUTER_GATEWAY: 192.168.100.1
#  SSL_ENABLE: false
  BGP_ASN: 65002
  ENCAP_PRIORITY: "MPLSoUDP,MPLSoGRE,VXLAN"
  RABBITMQ_NODE_PORT: 5673
  PHYSICAL_INTERFACE: eth1
  AUTH_MODE: keystone
  LOG_LEVEL: SYS_DEBUG
kolla_config:
  kolla_globals:
    kolla_internal_vip_address: 192.168.100.100
    contrail_api_interface_address: 192.168.100.100
    enable_ironic: no
    enable_swift: no
  kolla_passwords:
    metadata_secret: c0ntrail123
    keystone_admin_password: c0ntrail123