provider_config:
  bms:
    ssh_pwd: c0ntrail123
    ssh_user: root
    ntpserver: 192.168.122.1
    domainsuffix: local

instances:
  all-cont-dc-1:
    provider: bms
    ip:  192.168.122.151
    roles:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      openstack:
      vrouter:
  all-cont-dc-2:
    provider: bms
    ip:  192.168.122.152
    roles:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      openstack:
  all-cont-dc-3:
    provider: bms
    ip:  192.168.122.153
    roles:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      openstack:
global_configuration:
   CONTAINER_REGISTRY: hub.juniper.net/contrail
   CONTAINER_REGISTRY_USERNAME: JNPR-FieldUser1
   CONTAINER_REGISTRY_PASSWORD: Mvb!%3D_+i*Gx0pQg8^4
   REGISTRY_PRIVATE_INSECURE: True
contrail_configuration:
  CONTRAIL_VERSION: 5.0.0-0.40-ocata
  CLOUD_ORCHESTRATOR: openstack
  RABBITMQ_NODE_PORT: 5673
  VROUTER_GATEWAY: 192.168.100.1
  PHYSICAL_INTERFACE: eth1
  UPGRADE_KERNEL: true
  AUTH_MODE: keystone
  KEYSTONE_AUTH_URL_VERSION: /v3
kolla_config:
  kolla_globals:
    kolla_internal_vip_address: 192.168.100.150
    kolla_external_vip_address: 192.168.122.150
    contrail_api_interface_address: 192.168.100.150
#    network_interface: "eht1"
#    kolla_external_vip_interface: "eth0"
#    enable_heat: "yes"
  kolla_passwords:
    keystone_admin_password: Juniper123

