global_configuration:
  CONTAINER_REGISTRY: ci-repo.englab.juniper.net:5010
  REGISTRY_PRIVATE_INSECURE: True
provider_config:
  kvm:
    image: CentOS-7-x86_64-GenericCloud-1805.qcow2 
    image_url: http://10.84.5.120/cs-customer/images
    ssh_pwd: c0ntrail123
    ssh_user: root
    ssh_public_key:
    ssh_private_key:
    vcpu: 7
    vram: 24576
    subnet_prefix: 192.168.222.0
    subnet_netmask: 255.255.255.0
    gateway: 192.168.222.1
    nameserver: 192.168.222.1
    ntpserver: 10.84.5.100  
    domainsuffix: sdn.lab
instances:
  all-cont-dc-1:
    provider: kvm
    host: 10.87.65.27
    bridge: br-management
    ip: 192.168.222.151
    additional_interfaces:
      - bridge: br-lan-dc
        ip: 192.168.100.151
        mask: 255.255.255.0
    roles:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      vrouter:
      openstack:
      openstack_compute:
  all-cont-dc-2:
    provider: kvm
    host: 10.87.65.27
    bridge: br-management
    ip: 192.168.222.152
    additional_interfaces:
      - bridge: br-lan-dc
        ip: 192.168.100.152
        mask: 255.255.255.0
    roles:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      vrouter:
      openstack:
      openstack_compute:
  all-cont-dc-3:
    provider: kvm
    host: 10.87.65.27
    bridge: br-management
    ip: 192.168.222.153
    additional_interfaces:
      - bridge: br-lan-dc
        ip: 192.168.100.153
        mask: 255.255.255.0
    roles:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      vrouter:
      openstack:
      openstack_compute:
  cont-pop1-1:
    vcpu: 2
    vram: 8192
    vdisk: 20G
    provider: kvm
    host: 10.87.65.27
    bridge: br-management
    ip: 192.168.222.161
    additional_interfaces:
      - bridge: br-lan-dc
        ip: 192.168.100.161
        mask: 255.255.255.0
    roles:
      control:
        SUBCLUSTER: 1
  cont-pop1-2:
    vcpu: 2
    vram: 8192
    vdisk: 20G
    provider: kvm
    host: 10.87.65.27
    bridge: br-management
    ip: 192.168.222.162
    additional_interfaces:
      - bridge: br-lan-dc
        ip: 192.168.100.162
        mask: 255.255.255.0
    roles:
      control:
        SUBCLUSTER: 1
  comp-pop1-1:
    vcpu: 4
    vram: 16384
    vdisk: 20G
    provider: kvm
    host: 10.87.65.27
    bridge: br-management
    ip: 192.168.222.165
    additional_interfaces:
      - bridge: br-lan-p1
        ip: 192.168.101.165
        mask: 255.255.255.0
    roles:
      vrouter:
        SUBCLUSTER: 1
        VROUTER_GATEWAY: 192.168.101.1
      openstack:
      openstack_compute:
contrail_configuration:
  CONTRAIL_VERSION: latest
  CONTROLLER_NODES: 192.168.222.151, 192.168.222.152, 192.168.222.153
  CONTROL_NODES: 192.168.100.151, 192.168.100.152, 192.168.100.153, 192.168.100.161, 192.168.100.162 
  UPGRADE_KERNEL: true
  CLOUD_ORCHESTRATOR: openstack
  VROUTER_GATEWAY: 192.168.100.1
  BGP_ASN: 65002
  ENCAP_PRIORITY: "MPLSoUDP,MPLSoGRE,VXLAN"
  RABBITMQ_NODE_PORT: 5673
  PHYSICAL_INTERFACE: eth1
  AUTH_MODE: keystone
  LOG_LEVEL: SYS_DEBUG
kolla_config:
  kolla_globals:
    kolla_external_vip_address: 192.168.222.100
    kolla_internal_vip_address: 192.168.100.100
    contrail_api_interface_address: 192.168.100.100
  kolla_passwords:
    metadata_secret: c0ntrail123
    keystone_admin_password: c0ntrail123

