---
# Package installation and daemon start

- name: Install packages on hosts
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - libguestfs
    - libguestfs-tools
    - libguestfs-tools
    - centos-release-openstack-ocata
    - virt-install
    - libvirt
    - libvirt-python
    - net-tools
    - tcpdump
    
- name: install KVM
  yum:
    name: qemu-kvm
    state: latest

- name: Install openvswitch
  yum:
    name: openvswitch
    state: latest
    
- name: Start libvirt
  systemd:
    state: started
    name: libvirtd
    enabled: True

- name: Start openvswitch
  systemd:
    state: started
    name: openvswitch
    enabled: True

- name: Stop iptables
  systemd:
    state: stopped
    name: firewalld
    enabled: False

# Enable nested virtualisation

- name: copy kvm-nested.conf for nest virtualisation
  copy:
    src: 'kvm-nested.conf'
    dest: '/etc/modprobe.d/kvm-nested.conf'

- name: remove kvm_intel module
  modprobe:
    name: kvm_intel
    state: absent

- name: restart kvm_intel module
  modprobe:
    name: kvm_intel
    state: present
  
- name: check nested virtualisation
  shell: cat /sys/module/kvm_intel/parameters/nested
  register: out

#- debug: var=out.stdout_lines
#  fail:
#    msg: "CONTRAIL_SCHEDULER can only be set to 'compose' or 'k8s'"
#  when: out not in ['compose', 'k8s']


# download vmx image

- name: Get {{ vmx_image_name }}
  get_url:
    url: "{{ vmx_download_url }}/{{ vmx_image_name }}"
    dest: /root/{{ vmx_image_name }}

- name: Create OVS bridges on KVM hosts
  template:
    src: "templates/vxlan_bridge.j2"
    dest: "/etc/sysconfig/network-scripts/ifcfg-br-{{ item.key }}"
  with_dict: "{{ topology.networks }}"

